swagger: 2.0
info:
  $ref: server/apiYaml/info/index.yaml
host: localhost:8080
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  $ref: server/apiYaml/paths/index.yaml
definitions:
  $ref: server/apiYaml/definitions/index.yaml